### ISSUE TITLE
Practice-App: Implementing API for Post-info - Enhancements 

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#135]
**To Do:**

- Country name that is used for retrieving covid19 cases will be made case-insensitive. 
- A little note will be added asking user to enter the category id, not the name of it, to the page where the forms exist avoid any confusion. 

**Task Deadline:** 18.05.2022 16:00
**Review Deadline:** 18.05.2022 20:00

**Reviewers:** @yavuuzsameet , @Keremgunduz7

**Comment by yavuuzsameet** [comment]
I have also changed the necessary parts of my code to be case-insensitive. All consistent. I will push the code at the end of the day.

**Comment by kardelendemiral** [comment]
**A further thing to do:**

- Error heading will be added for the case where invalid values are entered when updating a post.

**Comment by kardelendemiral** [comment]
- Error heading is added for the case where invalid values are entered when updating a post.
- API used for retrieving covid19 cases is changed since the other one does not work sometimes.
- Country name that is used for retrieving covid19 cases is made case-insensitive.
- A little note is added asking user to enter the category id, not the name of it, to the page where the forms exist to avoid any confusion.

See the relevant pull request: #138 

Need review.

**Comment by yavuuzsameet** [comment]
I merged the request and reviewed it, all is good.

**Comment by Keremgunduz7** [comment]
I have also reviewed the code and the parts that you have changed. Since it is much more similar to Samet's project, it is more convenient to take advices from him rather than me :)

All in all, everything seems great and beautiful at this stage. It is also already merged.
After some time, if there will occurs no other problem or error to solve, we may close this issue. 
It can stay open for now.

**Comment by kardelendemiral** [comment]
Thanks for the review. I am closing the issue.
