### ISSUE TITLE
Creating Login and Signup pages for Frontend

### ISSUE THREAD

**Issue by burakmert236** [bounswe/bounswe2022group5#202]
***Description*:**

A sign-up screen where users and doctors can enter the required information for sign-up will be created for the frontend application. Required fields for users and doctors will be specialized. A login page will be implemented where users and doctors can log in with their e-mails and passwords.

***Todo's*:**
- [x] Signup page will be created.
- [x] Login page will be created.

***Reviewer*:** @Keremgunduz7  

***Task Deadline*:** 25.10.2022 10:00
***Review Deadline*:** 25.10.2022 12:00

**Comment by burakmert236** [comment]
I created basic structure of login and signup pages without backend integration, I pushed my code to this [branch](https://github.com/bounswe/bounswe2022group5/tree/frontend/feature/login-signup/%23202).

**Comment by Keremgunduz7** [comment]
Seems Look good to me. The background detail fits well. 
Assuming that you've created mock login data while implementing since the backend functionality has not completed yet, for now its ok, but maybe we can try it again with the real data when it is fed from our backend side.
Overall,
Thanks a lot for your efforts. 
Great work.
We can close the issue if you do not have anything to add in terms of this topic.

**Comment by burakmert236** [comment]
Since related pull request is merged, I am closing the issue
