### ISSUE TITLE
Editing Chatbot Requirements

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#50]
#### To Do:
-Chatbot Requirements will be edited according to the recent Meetings and Customer Meetings. [Chatbot](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1122-chat-bot-) section of the Requirements Page.

Reviewer: @bbenginbestas @enginoguzhansenol 

#### Review Deadline: 03.04.2022 - 20:00 GMT+3

**Comment by mehmetemreakbulut** [comment]
Some fundamental requirements are added to [page](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1122-chat-bot-).

**Comment by canberkboun9** [comment]
1.1.2.2.4 Registered users shall be able to ask some sort of questions that lead to related posts and articles.

This requirement should be divided into three:

- Registered Users shall be able to answer given question with given answers by choosing one answer.
- Registered Users shall be able to use chatbot to learn which tags their discomfort is under.
- Chatbot shall offer some suggestions after the query including related tags to the discomfort and links to related articles and post under the given tags.

First two should be under User Requirements. The third, under System.

**Comment by mehmetemreakbulut** [comment]
Edited 1.1.2.4 after @canberkboun9's suggestion. Some requirements will be deleted also.

**Comment by canberkboun9** [comment]
In the [Customer Meeting 2](https://github.com/bounswe/bounswe2022group5/wiki/Customer-Meeting-2#discussion) it says:

> - Review on the requirements:
>   - Some of the chatbot requirements (1.2.4.2.1, 1.2.4.2.6) assumes chatbot will have NLP and relearning, which we decide the opposite and have a simple decision tree.

Therefore, we need to delete these requirements:

- 1.2.4.2.1 Chatbot shall be able to determine keywords of the complex user messages including several sentences even if sentences are grammatically incorrect.
- 1.2.4.2.6 Chatbot shall collect information about user behavior from conversations to advance chatbot accuracy and performance.

In addition:

- 1.2.4.2.2 Chatbot shall ask questions to the users for narrowing the possible scenarios if chatbot is not able to produce 3 or less solutions to the users’ questions.

We could edit the 3 to 5 to increase our _Recall_ while decreasing our _Precision_. Because, users may find it more convenient to have more options and choosing them by hand instead of our chatbot who will probably have less accuracy then we expect.

**Comment by canberkboun9** [comment]
Made the deletion and edition and edited the enumeration accordingly.

**Comment by bbenginbestas** [comment]
The chatbot requirements look great. It is obvious that you put a lot of work into it. Corrections from Canberk are on point, too.

**Comment by canberkboun9** [comment]
Closing the issue.
