### ISSUE TITLE
Meeting 10.2 Notes

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#78]
#### Description:
A page for the second meeting of the 10th week will be created and meeting notes will be uploaded.

Reviewer: @canberkboun9 
#### Review Deadline: 10.05.2022 - 20:00 GMT+3

**Comment by palahb** [comment]
I created [Meeting 10.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-10.2) page and uploaded my notes. Since it includes important information about our practice-app, it would be good for all the team to revise it at least once.

**Comment by canberkboun9** [comment]
It is well documented! Thanks

**Comment by yavuuzsameet** [comment]
In the [meeting notes](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-10.2), we stated that [this api](https://coronavirus.m.pipedream.net/) will be used in order to fetch COVID19 data. However, I suggest that we use [Coronavirus COVID19 API](https://documenter.getpostman.com/view/10808728/SzS8rjbc) since it offers more options to the developer. The documentation specifies several APIs, I will use the one stated as [summary](https://api.covid19api.com/summary). I believe it will be more useful for our purposes.

**Comment by Keremgunduz7** [comment]
@yavuuzsameet just like as Samet mentioned.
We (@palahb and @mehmetemreakbulut) have decided another weather forecast API for the external usage in our practice-app. We have used the API from [WeatherAPI.com](https://rapidapi.com/weatherapi/api/weatherapi-com/). It has 1 million request limit for free. Maybe we can leave it or change it in the meeting notes.

**Comment by canberkboun9** [comment]
Added the meeting notes to wiki home page.

**Comment by palahb** [comment]
I am closing the issue since it is not active.
